import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { pic1 } from '../public/images/images.js'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.header}>
        Become Fitter, Stronger & More Confident !
      </h1>
      <button className={styles.header_button}>Get Started</button>
      <Image src={pic1} width={100} height={100} />
    </>
  )
}
